name: Update Gallery JSON

on:
  push:
    paths:
      - "gallery/**"
  workflow_dispatch:
  schedule:
    # Every 2 hours Kathmandu time
    # Kathmandu is UTC+5:45, so convert to UTC
    # Runs at 00:15, 02:15, 04:15, ..., 22:15 UTC → 6:00, 8:00, 10:00, ..., 4:00 Kathmandu
    - cron: '15 0-22/2 * * *'

jobs:
  update-gallery:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo without default token
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2. Generate gallery.json
      - name: Generate gallery.json
        run: |
          echo "{" > gallery.json
          for year in gallery/*; do
            [ -d "$year" ] || continue
            yname=$(basename "$year")
            echo "  \"$yname\": [" >> gallery.json
            find "$year" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) | sort | while read file; do
              url="https://raw.githubusercontent.com/${{ github.repository }}/main/$file"
              echo "    \"$url\"," >> gallery.json
            done
            # Remove last comma
            sed -i '$ s/,$//' gallery.json
            echo "  ]," >> gallery.json
          done
          # Remove last comma and close JSON
          sed -i '$ s/,$//' gallery.json
          echo "}" >> gallery.json

      # 3. Commit and force-push only if changes exist
      - name: Commit and push
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "Biraj Rai"
          git config --global user.email "70630924+birajrai@users.noreply.github.com"
          git add gallery.json
          if ! git diff-index --quiet HEAD; then
            git commit -m "update:: new images added gallery.json"
            git push --force https://$PAT_TOKEN@github.com/calyanstudio/janaprabhat-gallery.git HEAD:main
          else
            echo "No changes detected, skipping commit."
          fi
